namespace: static

deployment:
  name: friedhofparty
  image: ghcr.io/torbencarstens/friedhofparty:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  replicas: 2
  ports:
  - 8080
  labels:
    app: friedhofparty
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

configmap:
  nginx:
    name: nginx-config

service:
  name: friedhofparty
  port: 8080
  targetPort: 8080
  appSelector: friedhofparty

ingress:
  hosts:
    - friedhof.party
    - m.friedhof.party
  secret: tls-friedhofparty
  issuer: letsencrypt-issuer
  name: friedhofparty
